export const PROTECTED_BASE_COMMIT =
  "d4fb619512e5e8227a6c397c7c19b05c2b1daddd";

export const PROTECTED_EXACT_FILES = [
  "server/fanwei_auto_read.mjs",
  "server/fanwei_bridge.mjs",
  "server/fanwei_local_helper.mjs",
  "server/fanwei_local_helper_cli.mjs",
  "server/fanwei_requirement_mapper.mjs",
  "server/fanwei_requirement_workbook.py",
  "server/candidate_course_assignment.mjs",
  "server/candidate_personal_fields.mjs",
  "server/candidate_tenant_payload.mjs",
  "server/candidate_list_parser.py",
  "server/room_assignment.mjs",
  "web/exam_task_view_model.mjs",
  "web/pages/AutoConfigPage.mjs",
  "web/pages/ExamListPage.mjs",
  "web/pages/ExamDetailPage.mjs",
  "web/pages/CandidateImportPage.mjs",
  "web/components/auto-config/AutoConfigLogs.mjs",
  "web/components/auto-config/AutoConfigProgress.mjs",
  "web/components/auto-config/ConfigPreview.mjs",
  "web/components/auto-config/FinalScreenshot.mjs",
  "web/components/auto-config/RequirementUpload.mjs",
];

export const PROTECTED_SENTINELS = {
  "server/easy_exam_server.mjs": [
    "/api/fanwei/requirement-preview",
    "/api/fanwei/auto-read",
    "handleCandidateImport",
    "handleExamList",
    "handleCreateJob",
  ],
  "outputs/web_prototype/easy_exam_automation.html": [
    "autoConfigStack",
    "examListView",
    "candidateImportPanel",
    "fanweiRequirementTable",
  ],
};

export const PROTECTED_SHARED_REGIONS = {
  "server/easy_exam_server.mjs": [
    { name: "import workbook task creation", kind: "js-block", startAnchor: "async function createImportFromWorkbook({" },
    { name: "auto-config job state", kind: "js-block", startAnchor: "function createJob(importRecord, login) {" },
    { name: "auto-config progress events", kind: "js-block", startAnchor: "function pushEvent(job, evt) {" },
    { name: "Fanwei preview handler", kind: "js-block", startAnchor: "async function handleFanweiRequirementPreview(req, res) {" },
    { name: "Fanwei import task creation", kind: "js-block", startAnchor: "async function createFanweiRequirementImportFromPayload(payload, req, options = {}) {" },
    { name: "Fanwei import handler", kind: "js-block", startAnchor: "async function handleFanweiRequirementImport(req, res) {" },
    { name: "Fanwei auto-read status handler", kind: "js-block", startAnchor: "async function handleFanweiAutoReadStatus(_req, res) {" },
    { name: "Fanwei local-read handler", kind: "js-block", startAnchor: "async function handleFanweiLocalRead(req, res) {" },
    { name: "Fanwei auto-read handler", kind: "js-block", startAnchor: "async function handleFanweiAutoRead(req, res) {" },
    { name: "candidate parse handler", kind: "js-block", startAnchor: "async function handleCandidateParse(req, res) {" },
    { name: "candidate template handler", kind: "js-block", startAnchor: "async function handleCandidateTemplate(req, res) {" },
    { name: "candidate session list handler", kind: "js-block", startAnchor: "async function handleSessions(req, res) {" },
    { name: "candidate import handler", kind: "js-block", startAnchor: "async function handleCandidateImport(req, res) {" },
    { name: "candidate room preview handler", kind: "js-block", startAnchor: "async function handleRoomsPreview(sessionId, req, res) {" },
    { name: "candidate room auto handler", kind: "js-block", startAnchor: "async function handleRoomsAuto(sessionId, req, res) {" },
    { name: "auto-config create handler", kind: "js-block", startAnchor: "async function handleCreateJob(req, res) {" },
    { name: "auto-config progress state handler", kind: "js-block", startAnchor: "function handleJobState(job, res) {" },
    { name: "auto-config events handler", kind: "js-block", startAnchor: "function handleEvents(job, req, res) {" },
    { name: "exam list handler", kind: "js-block", startAnchor: "async function handleExamList(req, res) {" },
    { name: "exam detail handler", kind: "js-block", startAnchor: "async function handleTaskDetail(taskId, req, res) {" },
    { name: "Fanwei preview route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/fanwei/requirement-preview\") {" },
    { name: "Fanwei import route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/fanwei/requirement-import\") {" },
    { name: "Fanwei status route", kind: "js-block", startAnchor: "if (req.method === \"GET\" && url.pathname === \"/api/fanwei/auto-read/status\") {" },
    { name: "Fanwei local-read route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/fanwei/local-read\") {" },
    { name: "Fanwei auto-read route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/fanwei/auto-read\") {" },
    { name: "auto-config create route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/jobs\") {" },
    { name: "exam list route", kind: "js-block", startAnchor: "if (req.method === \"GET\" && url.pathname === \"/api/exams\") {" },
    { name: "exam detail route", kind: "anchor-range", startAnchor: "const taskDetailMatch = url.pathname.match(", endAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/candidates/parse\") {" },
    {
      name: "server dispatcher with approved PR 5 route slots",
      kind: "allowlisted-anchor-range",
      startAnchor: "async function requestHandler(req, res) {",
      endAnchor: "const roomsPreviewMatch = url.pathname.match(",
      allowedInsertions: [
        {
          name: "operation batch reconcile route",
          kind: "js-route-pair",
          startAnchor: "const operationBatchReconcileMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-batch\\/reconcile$/);",
          routeAnchor: "if (req.method === \"POST\" && operationBatchReconcileMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
        {
          name: "operation personnel state route",
          kind: "js-route-pair",
          startAnchor: "const personnelStateMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-personnel-task$/);",
          routeAnchor: "if (req.method === \"GET\" && personnelStateMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
        {
          name: "operation personnel preview route",
          kind: "js-route-pair",
          startAnchor: "const personnelPreviewMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-personnel-task\\/preview$/);",
          routeAnchor: "if (req.method === \"POST\" && personnelPreviewMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
        {
          name: "operation personnel send route",
          kind: "js-route-pair",
          startAnchor: "const personnelSendMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-personnel-task\\/send$/);",
          routeAnchor: "if (req.method === \"POST\" && personnelSendMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
        {
          name: "operation personnel attempt route",
          kind: "js-route-pair",
          startAnchor: "const personnelAttemptMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-personnel-task\\/attempts\\/([^/]+)$/);",
          routeAnchor: "if (req.method === \"GET\" && personnelAttemptMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
        {
          name: "operation personnel recheck route",
          kind: "js-route-pair",
          startAnchor: "const personnelRecheckMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)\\/operation-personnel-task\\/recheck$/);",
          routeAnchor: "if (req.method === \"POST\" && personnelRecheckMatch) {",
          afterAnchor: "if (req.method === \"POST\" && taskRetryMatch) {",
          beforeAnchor: "const sharedSheetFillMatch = url.pathname.match(",
        },
      ],
    },
    { name: "candidate parse route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/candidates/parse\") {" },
    { name: "candidate template route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/candidates/generate-template\") {" },
    { name: "candidate session list route", kind: "js-block", startAnchor: "if (req.method === \"GET\" && url.pathname === \"/api/sessions\") {" },
    { name: "candidate import route", kind: "js-block", startAnchor: "if (req.method === \"POST\" && url.pathname === \"/api/candidates/import\") {" },
    { name: "candidate room preview route", kind: "anchor-range", startAnchor: "const roomsPreviewMatch = url.pathname.match(", endAnchor: "const monitorAccountsMatch = url.pathname.match(" },
    { name: "candidate room auto route", kind: "anchor-range", startAnchor: "const roomsAutoMatch = url.pathname.match(", endAnchor: "if (req.method === \"GET\" && url.pathname.startsWith(\"/api/jobs/\") && url.pathname.endsWith(\"/events\")) {" },
    { name: "auto-config events route", kind: "js-block", startAnchor: "if (req.method === \"GET\" && url.pathname.startsWith(\"/api/jobs/\") && url.pathname.endsWith(\"/events\")) {" },
    { name: "auto-config state route", kind: "js-block", startAnchor: "if (req.method === \"GET\" && url.pathname.startsWith(\"/api/jobs/\")) {" },
  ],
  "outputs/web_prototype/easy_exam_automation.html": [
    { name: "auto-config view", kind: "html-section", startAnchor: "<section class=\"stack\" id=\"autoConfigStack\" hidden>" },
    { name: "candidate import view", kind: "html-section", startAnchor: "<section class=\"panel candidate-panel\" id=\"candidateImportPanel\" hidden>" },
    { name: "Fanwei view", kind: "html-section", startAnchor: "<section class=\"task-view\" id=\"fanweiTestView\" hidden>" },
    { name: "exam list view", kind: "html-section", startAnchor: "<section class=\"task-view\" id=\"examListView\" hidden>" },
    { name: "exam detail view", kind: "html-section", startAnchor: "<section class=\"task-view\" id=\"taskDetailView\" hidden>" },
    { name: "task progress derivation", kind: "js-block", startAnchor: "function taskConfigurationProgressFromSteps(progressSteps, fallbackProgress = 0) {" },
    { name: "current task progress", kind: "js-block", startAnchor: "function currentTaskProgress(task) {" },
    { name: "exam list render", kind: "js-block", startAnchor: "function renderExamList() {" },
    { name: "exam list load", kind: "js-block", startAnchor: "async function loadExams() {" },
    { name: "exam detail render", kind: "js-block", startAnchor: "function renderTaskDetail(task, options = {}) {" },
    { name: "exam detail load", kind: "js-block", startAnchor: "async function openTaskDetail(taskId) {" },
    { name: "candidate render", kind: "js-block", startAnchor: "function renderCandidateResult() {" },
    { name: "candidate parse", kind: "js-block", startAnchor: "async function parseCandidateFile(file) {" },
    { name: "candidate sessions load", kind: "js-block", startAnchor: "async function loadCandidateSessions() {" },
    { name: "candidate task context", kind: "js-block", startAnchor: "async function loadCandidateTaskContext() {" },
    { name: "candidate room assignment", kind: "js-block", startAnchor: "async function autoAssignRoomsAfterImport() {" },
    { name: "candidate import", kind: "js-block", startAnchor: "async function importCandidatesToSession() {" },
    { name: "auto-config progress display", kind: "js-block", startAnchor: "function setProgress(percent, caption, stageIndex) {" },
    { name: "auto-config import result", kind: "js-block", startAnchor: "function applyImportResult(fileName, data) {" },
    { name: "auto-config workbook import", kind: "js-block", startAnchor: "async function importWorkbook(file) {" },
    { name: "Fanwei preview render", kind: "js-block", startAnchor: "function renderFanweiModel(model = {}) {" },
    { name: "Fanwei enter auto-config", kind: "js-block", startAnchor: "async function enterFanweiAutoConfig(data, serialNo) {" },
    { name: "Fanwei preview read", kind: "js-block", startAnchor: "async function copyFanweiReaderScript() {" },
    { name: "Fanwei auto-read status", kind: "js-block", startAnchor: "async function loadFanweiAutoReadStatus() {" },
    { name: "Fanwei requirement import", kind: "js-block", startAnchor: "async function createFanweiRequirementImport() {" },
    { name: "auto-config progress event wiring", kind: "js-block", startAnchor: "function connectEvents(jobId, requirementIndex = uiState.autoConfigRequirementIndex) {" },
    { name: "protected page registration", kind: "js-array", startAnchor: "const pages = [" },
    { name: "candidate import wiring", kind: "js-call", startAnchor: "candidateImportBtn.addEventListener(\"click\", async () => {" },
    { name: "Fanwei preview wiring", kind: "js-call", startAnchor: "fanweiCopyScriptBtn.addEventListener(\"click\", () => copyFanweiReaderScript().catch((error) => {" },
    { name: "Fanwei import wiring", kind: "js-call", startAnchor: "fanweiImportBtn.addEventListener(\"click\", () => createFanweiRequirementImport().catch((error) => {" },
    { name: "auto-config creation wiring", kind: "js-call", startAnchor: "runBtn.addEventListener(\"click\", async () => {" },
  ],
};
